### ISSUE TITLE
Add attachment to send message node

### ISSUE THREAD

**Issue by fagiothree** [IDEMSInternational/rapidpro-flow-toolkit#59]
https://github.com/IDEMSInternational/rapidpro-flow-toolkit/blob/0c293c4cd278ad836c5204898b00f7e2f6e56333/rapidpro/models/actions.py#L83

The syntax should be
"attachments": [ "image:@(fields.comic_path & \"communicating_to_baby_comic_2.png\")"]
"attachments": ["audio:@(fields.voiceover_audio_path & \"One_On_One_Time_Children.mp3\")"]
"attachments": [ "video:@(fields.voiceover_video_path & \"One_On_One_Time_Teens.m4v\")"]
but the image\audio\video bit is missing

**Comment by geoo89** [comment]
fixed by 1854eba
