### ISSUE TITLE
Confirm which versions of python are supported.

### ISSUE THREAD

**Issue by geoo89** [IDEMSInternational/rapidpro-flow-toolkit#89]
`parsers/common/rowparser.py` uses some internal python functionality that may change across versions.

I expect this to work for python 3.6-3.9, but it would be good to test against these versions explicitly upon pushes, and also check whether the code is working for python >= 3.10.

**Comment by istride** [comment]
Is it possible to focus support on the currently supported versions of Python as per [Status of Python Versions](https://devguide.python.org/versions/)? The would be 3.8 - 3.11, at the moment.
